version: "3.3"

services:
  
  shortlink:
    image: shortlink:v1.0.0
    container_name: shortlink
    environment:
      - DB=${DB}
    volumes:
      - ./configs/dbconfig.yml:/configs/dbconfig.yml
    restart: always
    ports:
      - "8000:8000"
    network_mode: "host"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qweasd
    volumes:
      - ./sql/script.sql:/var/lib/postgressql/data/script.sql
    ports:
      - "5432:5432"
    # command: ["psql --user postgres", "\\i var/lib/postgressql/data/script.sql"]
